### ISSUE TITLE
Provide the way to avoid defining default mapping

### ISSUE THREAD

**Issue by mopp** [prakashdanish/vim-githubinator#6]
@prakashdanish 
Thanks for your nice plugin 🎉 

It is better to define `<Plug>` mapping (see `:help <Plug>`).
Default mapping may conflict user defined mapping.

However, this plugin also provide the default mapping.
The below steps are best to keep current behavior of this nice plugin.
1. Define `<Plug>` mappings
2. Re-define the current mapping (`gho` and `ghc`) using them.
3. Provide option to disable them such as `g:githubinator_no_default_mapping`
 
Of cause I can work for PR ! 😄  if you allow them.

**Comment by danishprakash** [comment]
@mopp thanks a lot for bringing this up. This is definitely a better approach, I'd suggest you go ahead if you have the time, I have this on todo anyways.

**Comment by mopp** [comment]
Thanks !
I'm going to create PR 👍
